### ISSUE TITLE
Practica Conexión De Base De Datos 

### ISSUE THREAD

**Issue by Yareli-Perez** [SistemasTecTlaxiaco/conexion-bases-de-datos-topicos4yan#1]
[Practica de Conexión de Bases de Datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-topicos4yan/files/8774443/Practica.de.Conexion.de.Bases.de.Datos.pdf)

**Comment by Gregorio012** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
