### ISSUE TITLE
Practica 7 Noelia

### ISSUE THREAD

**Issue by NoeliaGlez** [SistemasTecTlaxiaco/conexion-bases-de-datos-topicos4yan#2]
[Practica 7 Noelia.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-topicos4yan/files/8914386/Practica.7.Noelia.pdf)

**Comment by Litzy-lopez4** [comment]
17.8%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
